# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: de19da75daf14143ddf527d2875dd39c8e9e6e43f3b8dda5361ef99465d50dd3c7f03af8498b9f05716f4e9bff0767b73559c188d6c360955ea5a0fd9632bbd4

test:
  domain_name: example.com 
  secret_key_base: 3072af3ca69313c02c91a8c3a29f247d232fa366d6a37aa7923ada790cd26a8f5e956baa473a62a9a5861be8f0215c18d54d67efd64291e9b9c0d0d6c9bd85ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
